services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: always
    ports:
      - 127.0.0.1:9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /opt/docker/stacks/mealie/data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      TZ: Asia/Yekaterinburg
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.netsrm.ru
      # SMTP
      SMTP_HOST: mail.netsrm.ru
      SMTP_PORT: 587
      SMTP_FROM_NAME: mealie info
      SMTP_AUTH_STRATEGY: TLS
      SMTP_FROM_EMAIL: mealie-info@netsrm.ru
      SMTP_USER: mealie-info@netsrm.ru
      SMTP_PASSWORD: Str3800954
      # OpenID Connect
      OIDC_AUTH_ENABLED: true
      OIDC_SIGNUP_ENABLED: true
      OIDC_CONFIGURATION_URL: https://sso.netsrm.ru/application/o/mealie/.well-known/openid-configuration
      OIDC_CLIENT_ID: frmk5kbqFPthxEmLs3JbjK8KpFRMg9mvtQo1Lh1n
      OIDC_CLIENT_SECRET: tey0hoNeDLaB7fsNMP35xNUkVe0FI8SLbzw93E6Wzq45YPkMW1Issf2otRuH3LRto832ed0BYXGCFpNhSSh4ZtLUnWaUhdQzbbHucZDHSnIMTeaoxBuT2AU4KQSU9sG4
      OIDC_USER_GROUP: mealie-users
      OIDC_ADMIN_GROUP: SSO-Admins
      OIDC_AUTO_REDIRECT: true
      OIDC_REMEMBER_ME: true
      OIDC_PROVIDER_NAME: sso
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie328679812!
      POSTGRES_SERVER: postgres-mealie
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
    depends_on:
      postgres-mealie:
        condition: service_healthy
  postgres-mealie:
    container_name: postgres-mealie
    image: postgres:15
    restart: always
    volumes:
      - /opt/docker/stacks/mealie/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie328679812!
      POSTGRES_USER: mealie
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 30s
      timeout: 20s
      retries: 3
networks: {}
