services:
  StirlingPDF:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest-fat
    container_name: StirlingPDF
    deploy:
      resources:
        limits:
          memory: 8G
    depends_on:
      - StirlingPDF-db
    restart: always
    ports:
      - '8888:8080'
    volumes:
      - /opt/docker/stacks/StirlingPDF/configs:/configs
      - /opt/docker/stacks/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /opt/docker/stacks/StirlingPDF/customFiles:/customFiles/
      - /opt/docker/stacks/StirlingPDF/logs:/logs/
      - /opt/docker/stacks/StirlingPDF/pipeline:/pipeline/
    environment:
      DISABLE_ADDITIONAL_FEATURES: "false"
      SYSTEM_DEFAULTLOCALE: ru_RU
      SYSTEM_GOOGLEVISIBILITY: "false"
      METRICS_ENABLED: "true"
      # Oauth2 Settings
      SECURITY_ENABLELOGIN: true
      #SECURITY_LOGINMETHOD: "oauth2"
      SECURITY_OAUTH2_ENABLED: true
      SECURITY_OAUTH2_AUTOCREATEUSER: false
      SECURITY_OAUTH2_ISSUER: "<ISSUER_URI>"
      SECURITY_OAUTH2_CLIENTID: "<CLIENT_ID>"
      SECURITY_OAUTH2_CLIENTSECRET: "<CLIENT_SECRET>"
      SECURITY_OAUTH2_BLOCKREGISTRATION: false
      SECURITY_OAUTH2_SCOPES: "openid, profile, email"
      SECURITY_OAUTH2_USEASUSERNAME: email
      SECURITY_OAUTH2_PROVIDER: "authentik"
      # Database Settings
      SYSTEM_DATASOURCE_ENABLECUSTOMDATABASE: "true"
      SYSTEM_DATASOURCE_CUSTOMDATABASEURL: "jdbc:postgresql://StirlingPDF-db:5432/pdf"
      SYSTEM_DATASOURCE_USERNAME: "admin"
      SYSTEM_DATASOURCE_PASSWORD: "Sddsw232312"

  StirlingPDF-db:
    image: 'postgres:17.2-alpine'
    container_name: StirlingPDF-db
    volumes:
      - /opt/docker/stacks/StirlingPDF/pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: "pdf"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "Sddsw232312"