services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      # This line makes Actual available at port 5006 of the device you run the server on,
      # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
      - '127.0.0.1:5006:5006'
    environment:
      - ACTUAL_PORT=5006
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      - ACTUAL_OPENID_DISCOVERY_URL=https://sso.netsrm.ru/application/o/actual-budget/
      - ACTUAL_OPENID_CLIENT_ID=aKGCSuFMnU5uf9LR6h3utXHaTezYae0iwZGJx3Ue
      - ACTUAL_OPENID_CLIENT_SECRET=m8NhDGcRAqeFOaBVj5c9EcyOkiF0rb3rSjNkFinmIl2sGNhQha5poP1gexdEDNaflHZ27SKCvww4Cj2PiDPWS8EOO2IdHAqMj0zpZSboqIT03Ac0NMGmuQCAUmvlxivc
      - ACTUAL_OPENID_SERVER_HOSTNAME=https://actual.netsrm.ru
    volumes:
      - ./actual-data:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped