# SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

services:

  nextcloud-talk-recording:
    build:
      context: ..
      dockerfile: ./docker-compose/Dockerfile
    init: true
    shm_size: '4gb'
    restart: on-failure
    # By default the recording server is reachable through the network "nextcloud-talk-recording"
    # Depending on your setup (if you need to reach the recording server externally for example) you might need
    # to expose the used ports to the host machine, e.g.:
    ports:
      - "8000:8000"