services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 127.0.0.1:5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      - /opt/docker/stacks:/opt/docker/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/opt/docker/stacks
